# Use postgres/example user/password credentials
version: "3.8"

services:

  adminer:
    image: adminer
    restart: always
    depends_on:
      - pg
    ports:
      - 8080:8080
    networks: ['api']

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379

  pg:
    image: postgres:latest
    container_name: pg
    restart: always
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    depends_on:
      - redis
    volumes: 
      - database:/var/lib/postgresql/data
    networks: 
      - api


  api:
    container_name: api
    restart: always
    env_file: ./.env.local
    build: 
       context: ./
       target: production
    ports:
      - 4000:4000
    depends_on:
      - pg
      - redis
    links:
       - pg
#    volumes:
#        - api:/usr/app
#    networks: 
#        - api

volumes:
  database:
  # api:

networks:
  api:
    driver: bridge


