version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    depends_on:
      - db 
    #    environment:
      # - NGINX_HOST=localhost
      # - NGINX_PORT=80
# wait-for-db:
#   image: atkrad/wait4x
#   depends_on:
#     - db
#   command: tcp db:5432 -t 30s -i 250ms

# app:
#   build: .
#   restart: always
#   env_file:
#     - ./.env.local
#   depends_on:
#     wait-for-db:
#       condition: service_completed_successfully
#   ports:
#     - ${PORT}:${PORT}
#   environment:
#     ENVIRONMENT_NAME: 'docker'
