version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379

# wait-for-db:
#   image: atkrad/wait4x
#   depends_on:
#     - db
#   command: tcp db:5432 -t 30s -i 250ms

# app:
#   build: .
#   restart: always
#   env_file:
#     - ./.env.local
#   depends_on:
#     wait-for-db:
#       condition: service_completed_successfully
#   ports:
#     - ${PORT}:${PORT}
#   environment:
#     ENVIRONMENT_NAME: 'docker'
